apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghgl-sa
  namespace: ghgl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ghgl-role
  namespace: ghgl
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ghgl-rolebinding
  namespace: ghgl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ghgl-role
subjects:
- kind: ServiceAccount
  name: ghgl-sa
  namespace: ghgl
